# Generated by Django 6.0.3 on 2026-03-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprogram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_hours',
            field=models.PositiveIntegerField(),
        ),
    ]
