# Generated by Django 6.0.3 on 2026-03-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprogram', '0003_delete_course_remove_student_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='ticket',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(),
        ),
    ]
