# Generated by Django 6.0.3 on 2026-05-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('year_of_study', models.IntegerField()),
                ('student_id', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
