# Generated by Django 6.0.2 on 2026-04-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ПІБ')),
                ('year', models.IntegerField(verbose_name='Рік навчання')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='Студентський квиток')),
            ],
        ),
    ]
