# Generated by Django 6.0.2 on 2026-04-01 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('full_name', models.CharField(max_length=150)),
                ('year_of_study', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
