# Generated by Django 6.0.2 on 2026-04-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql', '0002_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
