# Generated by Django 6.0.4 on 2026-04-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab10_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stud_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
