# Generated by Django 6.0.2 on 2026-05-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва курсу')),
                ('duration_hours', models.IntegerField(verbose_name='Тривалість (годин)')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ПІБ')),
                ('year_of_study', models.IntegerField(verbose_name='Курс')),
                ('student_id', models.CharField(max_length=50, unique=True, verbose_name='Номер студентського')),
            ],
        ),
    ]
