# Generated by Django 5.2 on 2025-04-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('student_card', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
